ci: force missing include for java
Otherwise JNAetor enry.jar binding generation on
CI using `make all` results in

```
 /home/travis/build/bzz/enry/java/shared/libenry.h:8:0:
  error: File not found: stddef.h in
  . /usr/include /usr/local/include /usr/include/c++/4.8.4 /usr/include/c++/4.8.4/tr1
```

Signed-off-by: Alexander Bezzubov <bzz@apache.org>